#!/bin/zsh
DIRECTORY=`pwd`
script_file=$HOME/seabot2/seabot2-tools/seabot2-log-analyzer/seabot2_log_analyzer.py

START_DATE=""
for entry in $@; do
	if [[ "$entry" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}\ [0-9]{2}:[0-9]{2}:[0-9]{2}$ ]]; then
		START_DATE="$entry"
		echo "Starting date = " $START_DATE
	fi
done

for entry in $@; do
	if [[ "$entry" != "$START_DATE" ]]; then
		python3 $script_file $DIRECTORY/$entry $START_DATE
	fi
done